CREATE TABLE party_type
(
		type_id					INT				NOT NULL		CONSTRAINT PARTY_TYPE_PK PRIMARY KEY
	,	type_name				VARCHAR(128)	NOT NULL		CONSTRAINT PARTY_TYPE_NAME_UQ UNIQUE
	,	processed				DATETIME2		NOT NULL 		CONSTRAINT PARTY_TYPE_PROCESSED_DF DEFAULT GETDATE()
);