CREATE TABLE work_order_type
(
		name					VARCHAR(128)		NOT NULL
	,	description				VARCHAR(256)
	,	estimate				BIT					NOT NULL		CONSTRAINT WORK_ORDER_TYPE_ESTIMATE_DF DEFAULT (0)
	,	capitalize				BIT					NOT NULL		CONSTRAINT WORK_ORDER_TYPE_CAPITALIZED_DF DEFAULT (0)
	,	processed				DATETIME2			NOT NULL 		CONSTRAINT WORK_ORDER_TYPE_PROCESSED_DF DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT WORK_ORDER_TYPE_PK
		PRIMARY KEY
		(
			name
		)
)