CREATE TABLE relationship_type
(
		type_id	INT				NOT NULL		CONSTRAINT RELATIONSHIP_TYPE_PK PRIMARY KEY
	,	type_name VARCHAR(128)	NOT NULL		CONSTRAINT RELATIONSHIP_TYPE_NAME_UQ UNIQUE
	,	processed				DATETIME2		NOT NULL 		CONSTRAINT RELATIONSHIP_TYPE_PROCESSED_DF DEFAULT GETDATE()
)