CREATE TABLE Person
(
		PartyId					BIGINT			NOT NULL		CONSTRAINT PERSON_PK PRIMARY KEY
	,	FirstName				VARCHAR(128)	NOT NULL
	,	LastName				VARCHAR(128)	NOT NULL
	,	DateOfBirth				DATE
	,	IdentityNumber			VARCHAR(32)						CONSTRAINT IDENTITY_NUMBER_UQ UNIQUE
	,	ProcessedDateTime		TIMESTAMP		NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT PERSON_PARTY_FK
		FOREIGN KEY
		(
			PartyId
		)
		REFERENCES Party
		(
			PartyId
		)
);