CREATE TABLE Organization
(
		PartyId				BIGINT			NOT NULL		CONSTRAINT ORGANIZATION_PK PRIMARY KEY
	,	Name				VARCHAR(128)	NOT NULL
	,	DateOfRegistration	DATE
	,	RegistrationNumber	VARCHAR(32)						CONSTRAINT REGISTRATION_NUMBER_UQ UNIQUE
	,	ProcessedDateTime	TIMESTAMP		NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT ORGANIZATION_PARTY_FK
		FOREIGN KEY
		(
			PartyId
		)
		REFERENCES Party
		(
			PartyId
		)
);