
INSERT INTO PARTYNAME (LABELLEDBYPARTYID, NAME, PARTYNAMETYPE, ISSUEDBYPARTYID, COMMENT, EFD, ETD) VALUES
	(
			(SELECT PartyId FROM ORGANIZATION WHERE NAME = 'Company')
		,	'Company Plc'
		,	'CorporateName'
		,	NULL
		,	'Company incorporation name'
		,	'2008-01-01 00:00:00'
		,	NULL
	);

INSERT INTO PARTYNAME (LABELLEDBYPARTYID, NAME, PARTYNAMETYPE, ISSUEDBYPARTYID, COMMENT, EFD, ETD) VALUES
	(
			(SELECT PartyId FROM PERSON WHERE LASTNAME = 'Ashworth' AND DATEOFBIRTH = '1974-05-31')
		,	'Mark'
		,	'GivenName'
		,	NULL
		,	'First name'
		,	'1974-05-31 00:00:00'
		,	NULL
	);

INSERT INTO PARTYNAME (LABELLEDBYPARTYID, NAME, PARTYNAMETYPE, ISSUEDBYPARTYID, COMMENT, EFD, ETD) VALUES
	(
			(SELECT PartyId FROM PERSON WHERE LASTNAME = 'Ashworth' AND DATEOFBIRTH = '1974-05-31')
		,	'Phillip'
		,	'MiddleName'
		,	NULL
		,	'Middle name'
		,	'1974-05-31 00:00:00'
		,	NULL
	);

INSERT INTO PARTYNAME (LABELLEDBYPARTYID, NAME, PARTYNAMETYPE, ISSUEDBYPARTYID, COMMENT, EFD, ETD) VALUES
	(
			(SELECT PartyId FROM PERSON WHERE LASTNAME = 'Ashworth' AND DATEOFBIRTH = '1974-05-31')
		,	'Ashworth'
		,	'FamilyName'
		,	NULL
		,	NULL
		,	'1974-05-31 00:00:00'
		,	NULL
	);

INSERT INTO PARTYNAME (LABELLEDBYPARTYID, NAME, PARTYNAMETYPE, ISSUEDBYPARTYID, COMMENT, EFD, ETD) VALUES
	(
			(SELECT PartyId FROM PERSON WHERE LASTNAME = 'Ashworth' AND DATEOFBIRTH = '1975-01-10')
		,	'Natasja'
		,	'GivenName'
		,	NULL
		,	NULL
		,	'1975-01-10 00:00:00'
		,	'2014-12-06 23:59:59'
	);

INSERT INTO PARTYNAME (LABELLEDBYPARTYID, NAME, PARTYNAMETYPE, ISSUEDBYPARTYID, COMMENT, EFD, ETD) VALUES
	(
			(SELECT PartyId FROM PERSON WHERE LASTNAME = 'Ashworth' AND DATEOFBIRTH = '1975-01-10')
		,	'Olivier'
		,	'FamilyName'
		,	NULL
		,	NULL
		,	'1975-01-10 00:00:00'
		,	'2014-12-06 23:59:59'
	);

-- INSERT INTO PARTYNAME (LABELLEDBYPARTYID, NAME, PARTYNAMETYPE, ISSUEDBYPARTYID, COMMENT, EFD, ETD) VALUES
-- 	(
-- 			(SELECT PartyId FROM PERSON WHERE LASTNAME = 'Ashworth' AND DATEOFBIRTH = '1975-01-10')
-- 		,	'Olivier'
-- 		,	'MaidenName'
-- 		,	NULL
-- 		,	NULL
-- 		,	'2014-12-07 00:00:00'
-- 		,	NULL
-- 	);

INSERT INTO PARTYNAME (LABELLEDBYPARTYID, NAME, PARTYNAMETYPE, ISSUEDBYPARTYID, COMMENT, EFD, ETD) VALUES
	(
			(SELECT PartyId FROM PERSON WHERE LASTNAME = 'Ashworth' AND DATEOFBIRTH = '1975-01-10')
		,	'Ashworth'
		,	'FamilyName'
		,	NULL
		,	NULL
		,	'2014-12-07 00:00:00'
		,	NULL
	);

INSERT INTO RELATIONSHIP (RELATIONSHIPTYPEID, FROMPARTYID, TOPARTYID, EFD, ETD) VALUES
	(
			1
		,	(SELECT PartyId FROM ORGANIZATION WHERE NAME = 'Another')
		,	(SELECT PartyId FROM PERSON WHERE FirstName = 'Mark' AND LastName = 'Ashworth')
		,	'2001-01-01 00:00:00'
		,	'2008-11-30 23:59:59'
	);

INSERT INTO RELATIONSHIP (RELATIONSHIPTYPEID, FROMPARTYID, TOPARTYID, EFD, ETD) VALUES
	(
			1
		,	(SELECT PartyId FROM ORGANIZATION WHERE NAME = 'Company')
		,	(SELECT PartyId FROM PERSON WHERE FirstName = 'Mark' AND LastName = 'Ashworth')
		,	'2008-12-01 00:00:00'
		,	NULL
	);

INSERT INTO RELATIONSHIP (RELATIONSHIPTYPEID, FROMPARTYID, TOPARTYID, EFD, ETD) VALUES
	(
			1
		,	(SELECT PartyId FROM ORGANIZATION WHERE NAME = 'Company')
		,	(SELECT PartyId FROM PERSON WHERE FirstName = 'Natasja' AND LastName = 'Ashworth')
		,	'2008-12-01 00:00:00'
		,	NULL
	);