CREATE TABLE RelationshipType
(
		RelationshipTypeId	INT				NOT NULL		CONSTRAINT RELATIONSHIP_TYPE_PK PRIMARY KEY
	,	RelationshipTypeName VARCHAR(128)	NOT NULL		CONSTRAINT RELATIONSHIP_TYPE_NAME_UQ UNIQUE
)