CREATE TABLE WORK_ORDER_TYPE
(
		NAME					VARCHAR(128)		NOT NULL
	,	DESCRIPTION				VARCHAR(256)
	,	ESTIMATE				BOOLEAN				NOT NULL		DEFAULT FALSE
	,	CAPITALIZE				BOOLEAN				NOT NULL		DEFAULT FALSE
	,	PROCESSED				TIMESTAMP			NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT WORK_ORDER_TYPE_PK
		PRIMARY KEY
		(
			NAME
		)
)