CREATE TABLE Party_Name
(
		LABELLED_PARTY_ID		BIGINT				NOT NULL
	,	NAME					VARCHAR(256)		NOT NULL
	,	PARTY_NAME_TYPE			VARCHAR(128)		NOT NULL
	,	ISSUEDBY_PARTY_ID		BIGINT
	,	COMMENT					VARCHAR(256)
	,	EFD						TIMESTAMP			NOT NULL
	,	ETD						TIMESTAMP
	,	PROCESSED				TIMESTAMP			NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT PARTY_NAME_PK
		PRIMARY KEY
		(
			LABELLED_PARTY_ID
		,	Name
		)
	,	CONSTRAINT PARTY_NAME_LABELLED_BY_FK
		FOREIGN KEY
		(
			LABELLED_PARTY_ID
		)
		REFERENCES PARTY
		(
			PARTY_ID
		)
	,	CONSTRAINT PARTY_NAME_ISSUED_BY_FK
		FOREIGN KEY
		(
			ISSUEDBY_PARTY_ID
		)
		REFERENCES PARTY
		(
			PARTY_ID
		)
	,	CONSTRAINT PARTY_NAME_TYPE_FK
		FOREIGN KEY
		(
			Party_Name_Type
		)
		REFERENCES Party_Name_Type
		(
			Name
		)
)