CREATE TABLE WORK_ORDER 
(
		WORK_ORDER_ID				BIGINT				NOT NULL		GENERATED ALWAYS AS IDENTITY
	,	NAME						VARCHAR(128)		NOT NULL
	,	SCHEDULED_START				TIMESTAMP
	,	SCHEDULED_END				TIMESTAMP
	,	ACTUAL_START				TIMESTAMP
	,	ACTUAL_END					TIMESTAMP
	,	WORK_ORDER_TYPE				VARCHAR(128)		NOT NULL
	,	PROCESSED					TIMESTAMP			NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT WORK_ORDER_PK
		PRIMARY KEY
		(
			WORK_ORDER_ID
		)
	,	CONSTRAINT WORK_ORDER_NAME_UQ
		UNIQUE
		(
			NAME
		)
	,	CONSTRAINT WORK_ORDER_WORK_ORDER_TYPE_FK
		FOREIGN KEY
		(
			WORK_ORDER_TYPE
		)
		REFERENCES WORK_ORDER_TYPE
		(
			NAME
		)
)