CREATE TABLE TIMESHEET 
(
		TIMESHEET_ID				BIGINT				NOT NULL		GENERATED ALWAYS AS IDENTITY
	,	WORK_ORDER_ID				BIGINT
	,	SUBMIT_PARTY_ID				BIGINT
	,	APPROVE_PARTY_ID			BIGINT
	,	ACTIVITY_ID					BIGINT
	,	ACTIVITY_START				TIMESTAMP
	,	ACTIVITY_END				TIMESTAMP
	,	ACTIVITY_DURATION			INT
	,	COMMENT						VARCHAR(512)
	,	PROCESSED					TIMESTAMP			NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	APPROVED  					TIMESTAMP
	,	CONSTRAINT TIMESHEET_PK
		PRIMARY KEY
		(
			TIMESHEET_ID
		)
	,	CONSTRAINT TIMESHEET_WORK_ORDER_ID_FK
		FOREIGN KEY
		(
			WORK_ORDER_ID
		)
		REFERENCES WORK_ORDER
		(
			WORK_ORDER_ID
		)
)