CREATE TABLE Relationship_Type
(
		Type_Id	INT				NOT NULL		CONSTRAINT RELATIONSHIP_TYPE_PK PRIMARY KEY
	,	Type_Name VARCHAR(128)	NOT NULL		CONSTRAINT RELATIONSHIP_TYPE_NAME_UQ UNIQUE
	,	Processed				TIMESTAMP		NOT NULL 		DEFAULT CURRENT_TIMESTAMP
)