CREATE TABLE WORK_ORDER_ROLE_TYPE
(
		NAME					VARCHAR(128)		NOT NULL
	,	DESCRIPTION				VARCHAR(256)
	,	PROCESSED				TIMESTAMP			NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT WORK_ORDER_ROLE_TYPE_PK
		PRIMARY KEY
		(
			NAME
		)
)