CREATE TABLE EXTERNAL_ORGANIZATION
(
		PARTY_ID				BIGINT			NOT NULL
	,	NAME					VARCHAR(128)	NOT NULL
	,	REGISTRATION_DATE		DATE
	,	PROCESSED				TIMESTAMP		NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT EXTERNAL_ORG_PARTY_PK
		PRIMARY KEY
		(
			PARTY_ID
		)
	,	CONSTRAINT EXTERNAL_ORG_PARTY_FK
		FOREIGN KEY
		(
			PARTY_ID
		)
		REFERENCES Party
		(
			PARTY_ID
		)
);

CREATE TABLE INTERNAL_ORGANIZATION
(
		PARTY_ID				BIGINT			NOT NULL
	,	NAME					VARCHAR(128)	NOT NULL
	,	REGISTRATION_DATE		DATE
	,	PROCESSED				TIMESTAMP		NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT INTERNAL_ORG_PARTY_PK
		PRIMARY KEY
		(
			PARTY_ID
		)
	,	CONSTRAINT INTERNAL_ORG_PARTY_FK
		FOREIGN KEY
		(
			PARTY_ID
		)
		REFERENCES Party
		(
			PARTY_ID
		)
);