CREATE TABLE Person
(
		PARTY_ID				BIGINT			NOT NULL
	,	First_Name				VARCHAR(128)	NOT NULL
	,	Last_Name				VARCHAR(128)	NOT NULL
	,	BIRTH_DATE				DATE
	,	PROCESSED				TIMESTAMP		NOT NULL 		DEFAULT CURRENT_TIMESTAMP
	,	CONSTRAINT PERSON_PK PRIMARY KEY
		(
			PARTY_ID
		)
	,	CONSTRAINT PERSON_PARTY_FK
		FOREIGN KEY
		(
			PARTY_ID
		)
		REFERENCES Party
		(
			PARTY_ID
		)
);